#! /bin/sh

# start
polybar -r bar &
${HOME}/.fehbg &
dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor LVDS1 -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
